/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment13_2;

/**
 *
 * @author DELL
 */
public class Question3 extends javax.swing.JFrame implements Runnable
{

    /**
     * Creates new form Question3
     */
    volatile boolean flag=true;
     int x=1 ,y=1,z=1;
   
    public Question3()
    {
        initComponents();
        lblmilli.setText(String.valueOf(0));
        lblsec.setText(String.valueOf(0));
        lblmin.setText(String.valueOf(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        lblsec = new java.awt.Label();
        lblmin = new java.awt.Label();
        lblmilli = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        btnstop = new java.awt.Button();
        btnreset = new java.awt.Button();
        btnstart = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question3");

        panel1.setBackground(new java.awt.Color(0, 153, 153));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(51, 255, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 153, 153));
        label1.setText("STOPWATCH");

        lblsec.setAlignment(java.awt.Label.CENTER);
        lblsec.setBackground(new java.awt.Color(51, 255, 255));
        lblsec.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        lblmin.setAlignment(java.awt.Label.CENTER);
        lblmin.setBackground(new java.awt.Color(51, 255, 255));
        lblmin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        lblmilli.setAlignment(java.awt.Label.CENTER);
        lblmilli.setBackground(new java.awt.Color(51, 255, 255));
        lblmilli.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 255, 255));
        label5.setText("Seconds");

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(51, 255, 255));
        label6.setText("MilliSeconds");

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(51, 255, 255));
        label7.setText("Minutes");

        btnstop.setBackground(new java.awt.Color(255, 0, 0));
        btnstop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnstop.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnstop.setForeground(new java.awt.Color(255, 255, 51));
        btnstop.setLabel("Stop");
        btnstop.setName("Start"); // NOI18N
        btnstop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnstopActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 0, 0));
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 51));
        btnreset.setLabel("Reset");
        btnreset.setName("Start"); // NOI18N
        btnreset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnresetActionPerformed(evt);
            }
        });

        btnstart.setBackground(new java.awt.Color(255, 0, 0));
        btnstart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnstart.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnstart.setForeground(new java.awt.Color(255, 255, 51));
        btnstart.setLabel("Start");
        btnstart.setName("Start"); // NOI18N
        btnstart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnstartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(btnstart, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnstop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblmin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(lblsec, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnreset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(lblmilli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsec, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmilli, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnstop, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void run()
    {
       
        while(flag)
        {
            
                if(x<=1000)
                {
                     lblmilli.setText(String.valueOf(x));
                    try
                    {
                         Thread.sleep(1);
                    }
                    catch(InterruptedException e)
                    {
                        System.out.println("Caught"+ e);
                    }
                    x++;
                }
         
                if(x==1000)
                {
                    x=1;  
                     lblsec.setText(String.valueOf(y)); 
                      y++;
                }
                 if(y==60)
                {
                    lblmin.setText(String.valueOf(z));
                    z++;
                    y=1;
                }
        }  
    }
    private void btnstartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnstartActionPerformed
    {//GEN-HEADEREND:event_btnstartActionPerformed
        // TODO add your handling code here:
        Thread t1=new Thread(this);
        
        if(flag==false)
        {
            flag=true;
        }
        t1.start();
        
    }//GEN-LAST:event_btnstartActionPerformed

    private void btnstopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnstopActionPerformed
    {//GEN-HEADEREND:event_btnstopActionPerformed
        // TODO add your handling code here:
      flag=false;
        
    }//GEN-LAST:event_btnstopActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnresetActionPerformed
    {//GEN-HEADEREND:event_btnresetActionPerformed
        // TODO add your handling code here:
        lblmilli.setText(String.valueOf(0));
        lblsec.setText(String.valueOf(0));
        lblmin.setText(String.valueOf(0));
        x=y=z=1;
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Question3 ref=new Question3();
                ref.setVisible(true);
                ref.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnreset;
    private java.awt.Button btnstart;
    private java.awt.Button btnstop;
    private java.awt.Label label1;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label lblmilli;
    private java.awt.Label lblmin;
    private java.awt.Label lblsec;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
