/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment13_2;

import java.awt.CheckboxGroup;

/**
 *
 * @author DELL
 */
public class Question5 extends javax.swing.JFrame
{
    CheckboxGroup cbg=new CheckboxGroup();
    String gender,day,month,yr;
    /**
     * Creates new form Question5
     */
    public Question5()
    {
        initComponents();
        for(int i=1;i<=31;i++)
        {
            cmbday.add(String.valueOf(i));
        }
        for(int i=0;i<months.length;i++)
        {
            cmbmonth.add(months[i]);
        }
        for(int i=2000;i<=2006;i++)
        {
            cmbyr.add(String.valueOf(i));
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        label10 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        panel2 = new java.awt.Panel();
        chkfeamale = new java.awt.Checkbox();
        chkmale = new java.awt.Checkbox();
        panel3 = new java.awt.Panel();
        txtmname = new java.awt.TextField();
        txtlname = new java.awt.TextField();
        txtfname = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        panel4 = new java.awt.Panel();
        label9 = new java.awt.Label();
        chkcpp = new java.awt.Checkbox();
        chkds = new java.awt.Checkbox();
        chkads = new java.awt.Checkbox();
        chkc = new java.awt.Checkbox();
        chkjava = new java.awt.Checkbox();
        panel6 = new java.awt.Panel();
        cmbday = new java.awt.Choice();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        cmbyr = new java.awt.Choice();
        cmbmonth = new java.awt.Choice();
        txtarea = new java.awt.TextArea();
        button1 = new java.awt.Button();

        label10.setText("label10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question5");

        panel1.setBackground(new java.awt.Color(102, 102, 0));
        panel1.setPreferredSize(new java.awt.Dimension(534, 596));

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Student Registration");

        panel2.setBackground(new java.awt.Color(153, 153, 0));

        chkfeamale.setCheckboxGroup(cbg
        );
        chkfeamale.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkfeamale.setLabel("Female");
        chkfeamale.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkfeamaleItemStateChanged(evt);
            }
        });

        chkmale.setCheckboxGroup(cbg
        );
        chkmale.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkmale.setLabel("Male");
        chkmale.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkmaleItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(chkmale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(chkfeamale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkmale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkfeamale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        panel3.setBackground(new java.awt.Color(153, 153, 0));

        txtmname.setBackground(new java.awt.Color(102, 102, 0));
        txtmname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtmname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtmnameKeyTyped(evt);
            }
        });

        txtlname.setBackground(new java.awt.Color(102, 102, 0));
        txtlname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtlname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtlnameKeyTyped(evt);
            }
        });

        txtfname.setBackground(new java.awt.Color(102, 102, 0));
        txtfname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtfname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtfnameKeyTyped(evt);
            }
        });

        label2.setText("label2");

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Firstname");

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("MiddleName");

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("LastName");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        panel4.setBackground(new java.awt.Color(153, 153, 0));

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("Choose the subject you have interest in:");

        chkcpp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkcpp.setLabel("CPP");
        chkcpp.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkcppItemStateChanged(evt);
            }
        });

        chkds.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkds.setLabel("DS");
        chkds.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkdsItemStateChanged(evt);
            }
        });

        chkads.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkads.setLabel("ADS");
        chkads.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkadsItemStateChanged(evt);
            }
        });

        chkc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkc.setLabel("C");
        chkc.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkcItemStateChanged(evt);
            }
        });

        chkjava.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkjava.setLabel("Java");
        chkjava.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkjavaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(chkc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkcpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(chkds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(chkads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(chkjava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkcpp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chkads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkjava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        panel6.setBackground(new java.awt.Color(153, 153, 0));

        cmbday.setBackground(new java.awt.Color(102, 102, 0));
        cmbday.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbday.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cmbdayItemStateChanged(evt);
            }
        });

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setText("Day");

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText("Year");

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setText("Month");

        cmbyr.setBackground(new java.awt.Color(102, 102, 0));
        cmbyr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbyr.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cmbyrItemStateChanged(evt);
            }
        });

        cmbmonth.setBackground(new java.awt.Color(102, 102, 0));
        cmbmonth.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbmonth.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cmbmonthItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addComponent(cmbday, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbyr, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbyr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtarea.setBackground(new java.awt.Color(152, 153, 0));
        txtarea.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        button1.setBackground(new java.awt.Color(255, 0, 0));
        button1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 0));
        button1.setLabel("Submit");
        button1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGap(26, 26, 26))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtfnameKeyTyped
    {//GEN-HEADEREND:event_txtfnameKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z' || evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {}
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtfnameKeyTyped

    private void txtmnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtmnameKeyTyped
    {//GEN-HEADEREND:event_txtmnameKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z' || evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {}
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtmnameKeyTyped

    private void txtlnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtlnameKeyTyped
    {//GEN-HEADEREND:event_txtlnameKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z' || evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {}
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtlnameKeyTyped

    private void chkmaleItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkmaleItemStateChanged
    {//GEN-HEADEREND:event_chkmaleItemStateChanged
        // TODO add your handling code here:
        if(chkmale.getState())
        {
            gender="Male";
        }
    }//GEN-LAST:event_chkmaleItemStateChanged

    private void chkfeamaleItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkfeamaleItemStateChanged
    {//GEN-HEADEREND:event_chkfeamaleItemStateChanged
        // TODO add your handling code here:
        if(chkfeamale.getState()) 
        {
            gender="Female";
        }
    }//GEN-LAST:event_chkfeamaleItemStateChanged

    private void cmbdayItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbdayItemStateChanged
    {//GEN-HEADEREND:event_cmbdayItemStateChanged
        // TODO add your handling code here:
        day=cmbday.getSelectedItem();
    }//GEN-LAST:event_cmbdayItemStateChanged
    String[] months ={"Jan","Feb","March","April","May","June","July","August","September","October",
        "November","December"};
    String[]day30={"April","June","September","November"};
    boolean found(String month,String[]arr)
    {
        for(int i=0;i<arr.length;i++)
        {
            if(arr[i]==month)
            {
                return true;
            }
        }
        return false;
    }
    private void cmbmonthItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbmonthItemStateChanged
    {//GEN-HEADEREND:event_cmbmonthItemStateChanged
        // TODO add your handling code here:
        month=cmbmonth.getSelectedItem();
        if(day.equals("31") && found(month,day30))
        {
            CommonalertBox.showMsg(month+ " can't have 31 days ",this);
        }
        if(month.equals("Feb") && Integer.parseInt(day)>29)
        {
            CommonalertBox.showMsg("Invalid day selection",this);
        }
        
    }//GEN-LAST:event_cmbmonthItemStateChanged

    private void cmbyrItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbyrItemStateChanged
    {//GEN-HEADEREND:event_cmbyrItemStateChanged
        // TODO add your handling code here:
        yr=cmbyr.getSelectedItem();
        if(Integer.parseInt(yr)%4 !=0 && month=="Feb")
        {
            CommonalertBox.showMsg("Inavlid selection ",this);
            
        }
    }//GEN-LAST:event_cmbyrItemStateChanged
    String subjects="";
    private void chkcItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkcItemStateChanged
    {//GEN-HEADEREND:event_chkcItemStateChanged
        // TODO add your handling code here:
        if(chkc.getState())
        {
            subjects+=" C ";
        }
        else
        {
            subjects.replaceAll(" C ", "");
                    
        }
    }//GEN-LAST:event_chkcItemStateChanged

    private void chkcppItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkcppItemStateChanged
    {//GEN-HEADEREND:event_chkcppItemStateChanged
        // TODO add your handling code here:
         if(chkcpp.getState())
        {
            subjects+=" CPP ";
        }
        else
        {
            subjects.replaceAll(" CPP ", "");
                    
        }
    }//GEN-LAST:event_chkcppItemStateChanged

    private void chkdsItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkdsItemStateChanged
    {//GEN-HEADEREND:event_chkdsItemStateChanged
        // TODO add your handling code here:
         if(chkds.getState())
        {
            subjects+=" DS ";
        }
        else
        {
            subjects.replaceAll(" DS ", "");
                    
        }
    }//GEN-LAST:event_chkdsItemStateChanged

    private void chkadsItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkadsItemStateChanged
    {//GEN-HEADEREND:event_chkadsItemStateChanged
        // TODO add your handling code here:
         if(chkads.getState())
        {
            subjects+=" ADS ";
        }
        else
        {
            subjects.replaceAll(" ADS ", "");
                    
        }
    }//GEN-LAST:event_chkadsItemStateChanged

    private void button1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button1ActionPerformed
    {//GEN-HEADEREND:event_button1ActionPerformed
        // TODO add your handling code here:
        if(txtfname.getText().isEmpty()||txtmname.getText().isEmpty()||txtlname.getText().isEmpty()||day==null
                ||month==null ||yr==null ||gender==null)
        {
            CommonalertBox.showMsg("All fields are Required", this);
        }
        else
        {
          clearForm();   
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    private void chkjavaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkjavaItemStateChanged
    {//GEN-HEADEREND:event_chkjavaItemStateChanged
        // TODO add your handling code here:
         if(chkjava.getState())
        {
            subjects+=" JAVA ";
        }
        else
        {
            subjects.replaceAll(" JAVA ", "");
                    
        }
    }//GEN-LAST:event_chkjavaItemStateChanged
    void clearForm()
    {
        dispose();
        CommonalertBox.showMsg("Your Record saved Successfully!!!!", this);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Question5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Question5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Question5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Question5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Question5 ref=new Question5();
                ref.setVisible(true);
                ref.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Checkbox chkads;
    private java.awt.Checkbox chkc;
    private java.awt.Checkbox chkcpp;
    private java.awt.Checkbox chkds;
    private java.awt.Checkbox chkfeamale;
    private java.awt.Checkbox chkjava;
    private java.awt.Checkbox chkmale;
    private java.awt.Choice cmbday;
    private java.awt.Choice cmbmonth;
    private java.awt.Choice cmbyr;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel6;
    private java.awt.TextArea txtarea;
    private java.awt.TextField txtfname;
    private java.awt.TextField txtlname;
    private java.awt.TextField txtmname;
    // End of variables declaration//GEN-END:variables
}
